---
apiVersion: v1
kind: ConfigMap
metadata:
    namespace: es
    name: conf-website
data:
    nginx.conf: |
        env DOCKER_NAME_SERVER;

        worker_processes  1;

        error_log  /dev/stdout info;
        pid        /var/run/nginx.pid;

        events {
          worker_connections  1024;
        }

        http {
          include       /usr/local/openresty/nginx/conf/mime.types;
          default_type  application/octet-stream;

          log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                            '$status $body_bytes_sent "$http_referer" '
                            '"$http_user_agent" "$http_x_forwarded_for"';

          access_log  /dev/stdout  main;

          sendfile        on;
          #tcp_nopush     on;

          keepalive_timeout  65;

          gzip  on;
          gzip_disable "msie6";

          gzip_comp_level 6;
          gzip_min_length 4096;
          gzip_buffers 16 8k;
          gzip_proxied any;
          gzip_types
            text/plain
            text/css
            application/javascript
            application/json
            image/svg+xml;

          autoindex off;

          proxy_http_version 1.1;
          proxy_buffering off;
          proxy_set_header Host $http_host;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          # Mitigate httpoxy attack
          proxy_set_header Proxy "";

          resolver nameserver valid=10s ipv6=off;

          include /conf/*.inc;
        }
    server.inc: |
        server {
          listen       80;
          server_name  localhost;

          location = /favicon.ico {
            log_not_found off;
            access_log off;
          }

          location = /web {
            rewrite /web(.*) $scheme://$http_host/web/dingtalk.html$1 redirect;
          }

          location = /applet {
            rewrite /applet(.*) $scheme://$http_host/applet/dingtalk.html$1 redirect;
          }

          location = /web-msg {
            rewrite /web-msg(.*) $scheme://$http_host/applet/dingtalk-message-web.html$1 redirect;
          }

          location = /applet-msg {
            rewrite /applet-msg(.*) $scheme://$http_host/applet/dingtalk-message-applet.html$1 redirect;
          }

          location = /dingtalk-audit-message {
            rewrite /dingtalk-audit-message(.*) $scheme://$http_host/applet/dingtalk-audit-message.html$1 redirect;
          }

          location /web/ {
            alias /data/web/;
          }

          location /applet/ {
            alias /data/applet/;
          }

          location /static/ {
            add_header Cache-Control no-cache;
            alias /static/;
          }

          location /api/v1/bi/ {
            set $backend "";
            access_by_lua_block {
              ngx.var.backend = require("dns")("pivot-rest-server")
            }
            proxy_pass http://$backend:1338;
          }

          location /bi/ {
            set $backend "";
            access_by_lua_block {
              ngx.var.backend = require("dns")("print-server")
            }
            proxy_pass http://$backend;
          }

          location / {
            add_header Cache-Control no-cache;
            alias /static/;
          }
        }
---
apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: es
    name: website
spec:
    selector:
        matchLabels:
            app: website
    replicas: 1
    template:
        metadata:
            labels:
                app: website
        spec:
            containers:
                - name: website
                  image: docker.ekuaibao.com/openresty:1.13.6
                  imagePullPolicy: Always
                  volumeMounts:
                      - name: tz-config
                        mountPath: /etc/localtime
                      - name: conf
                        mountPath: /conf
                      - name: data
                        mountPath: /data
                      - name: static
                        mountPath: /static
                  ports:
                      - containerPort: 80
                        protocol: TCP
                        name: http
                  resources:
                      limits:
                          memory: 512Mi
                - name: web
                  image: docker.ekuaibao.com/whispered-web:${WEB_VERSION}-beta
                  imagePullPolicy: Always
                  volumeMounts:
                      - name: conf
                        mountPath: /conf
                      - name: data
                        mountPath: /data
                        subPath: web
                - name: applet
                  image: docker.ekuaibao.com/whispered-applet:${APPLET_VERSION}-beta
                  imagePullPolicy: Always
                  volumeMounts:
                      - name: conf
                        mountPath: /conf
                      - name: data
                        mountPath: /data
                        subPath: applet
            imagePullSecrets:
                - name: ekuaibao-repo
            nodeSelector:
                ekb.app: "true"
            volumes:
                - name: tz-config
                  hostPath:
                      path: /etc/localtime
                - name: conf
                  configMap:
                      name: conf-website
                - name: static
                  configMap:
                      name: conf-static
                - name: data
                  emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
    namespace: es
    name: website
spec:
    selector:
        app: website
    ports:
        - port: 80
          protocol: TCP
          name: http
